# Generated by Django 3.0.2 on 2020-01-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('origin', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('bio', models.TextField(max_length=2000)),
            ],
        ),
    ]
